apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarg
  labels:
    app: yarg
  namespace: yarg-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarg
  template:
    metadata:
      labels:
        app: yarg
    spec:
      containers:
        - name: yarg
          image: acrworkflow1691714185967.azurecr.io/image-workflow-1691714185967:latest
          ports:
            - containerPort: 80