apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-test-workflow
  labels:
    app: k8-test-workflow
  namespace: namespace-workflow-1691684123049
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-test-workflow
  template:
    metadata:
      labels:
        app: k8-test-workflow
    spec:
      containers:
        - name: k8-test-workflow
          image: acrworkflow1691684123049.azurecr.io/image-workflow-1691684123049:latest
          ports:
            - containerPort: 5173