apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-test
  labels:
    app: k8-test
  namespace: k8-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-test
  template:
    metadata:
      labels:
        app: k8-test
    spec:
      containers:
        - name: k8-test
          image: k8testregistry.azurecr.io/k8-test:latest
          ports:
            - containerPort: 3000