apiVersion: apps/v1
kind: Deployment
metadata:
  name: tester
  labels:
    app: tester
  namespace: k8-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tester
  template:
    metadata:
      labels:
        app: tester
    spec:
      containers:
        - name: tester
          image: k8testregistry.azurecr.io/k8-test-app:latest
          ports:
            - containerPort: 80