apiVersion: v1
kind: Service
metadata:
  name: k8-test-workflow
  namespace: namespace-workflow-1691684123049
spec:
  type: LoadBalancer
  selector:
    app: k8-test-workflow
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173